---

gems:
- name: rails
  version: '= 2.3.5'
- name: haml
  version: '=2.2.22'
- name: sqlite3-ruby
  version: '1.2.5'
- name: find_or_redirect
  version: '=0.2.1'
- name: twitter_oauth
  version: '=0.3.3'

<% if ENV['ENV'] && ENV['ENV']=='test' || ENV['ENV']=='all' %>
- name: rspec
  version: '=1.2.9' 
- name: rspec-rails
  version: '=1.2.9'
- name: shoulda
  version: '=2.10.3'
- name: webrat
  version: '=0.7.0'
- name: factory_girl
  version: '=1.2.4'
- name: hydra
  version: '=0.16.2'
<% end %>
